### ISSUE TITLE
Comments on "Dense Optical Flow Prediction from a Static Image"

### ISSUE THREAD

**Issue by erfannoury** [yassersouri/paper-notes#1]
> The paper claims that the problem with regression is "and output space which is smoothens results to the mean". (I think; isn't that where GANs shine?)

Actually this is a problem in GANs, too. There is a degenerate solution for GANs when model converges to the mean value of the modes (when the distribution has multiple modes).

**Comment by yassersouri** [comment]
yes, but new techniques have tried solving that problem in GANs.

https://arxiv.org/abs/1611.02163

**Comment by erfannoury** [comment]
I know, I'm just saying that it's a problem with the GANs, too, unless you use those tricks. In fact I think it's a problem with the maximum likelihood training, but I don't know the exact proof.

**Comment by yassersouri** [comment]
Maximum likelihood is the most widely used heuristic ever!

**Comment by erfannoury** [comment]
Calling it a heuristic is too strong of an opinion. I don't know what to say.
